import Head from 'next/head'

import { Inter } from '@next/font/google'
import Header from './../components/Header';
import Nav from '../components/Nav';
import requests from "../utils/requests";
import Results from '@/components/Results';
import axios from "axios";
const inter = Inter({ subsets: ['latin'] })

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />

      <Results results={results} />
    </>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await axios.get(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url
    }`
  );

  return {
    props: {
      results: request.data.results,
    },
  };
}
